// FILE: web/frontend/config/FILTERS.ts
//
// GENERATED FILE – DO NOT EDIT BY HAND
// Source of truth: web/lib/filters/registry.ts
//
// To regenerate:
//   npx ts-node web/scripts/generateFrontendFilters.ts
//   or
//   npx tsx web/scripts/generateFrontendFilters.ts

import type {
  FilterKey,
  FilterOperator,
  FilterScope,
  ValueKind,
  FilterWidget,
  FilterPlane,
} from "../../lib/filters/registry";

export interface FrontendFilterConfig {
  key: FilterKey;
  label: string;
  scope: FilterScope;
  plane: FilterPlane;
  valueKind: ValueKind;
  operators: FilterOperator[];
  widget: FilterWidget;
  placeholder?: string;
  multiSelect?: boolean;
  enumValues?: { value: string; label: string }[];
  fullText?: {
    vectorField: string;
    config?: string;
  };
}

export const FILTERS: FrontendFilterConfig[] = [
  {
    key: "product.category",
    label: "Category",
    scope: "product",
    plane: "FAST",
    valueKind: "string",
    operators: ["EQ", "NEQ", "IN", "NOT_IN", "CONTAINS", "NOT_CONTAINS", "STARTS_WITH", "ENDS_WITH", "IS_SET", "IS_NOT_SET"],
    widget: "text",
    placeholder: undefined,
    multiSelect: true,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "product.collection",
    label: "Collection",
    scope: "product",
    plane: "FAST",
    valueKind: "string",
    operators: ["EQ", "NEQ", "IN", "NOT_IN", "IS_SET", "IS_NOT_SET"],
    widget: "text",
    placeholder: undefined,
    multiSelect: true,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "product.createdAt",
    label: "Date Created",
    scope: "product",
    plane: "FAST",
    valueKind: "date",
    operators: ["EQ", "NEQ", "GT", "GTE", "LT", "LTE", "BETWEEN", "IS_SET", "IS_NOT_SET"],
    widget: "date",
    placeholder: undefined,
    multiSelect: undefined,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "product.description",
    label: "Description",
    scope: "product",
    plane: "FAST",
    valueKind: "text",
    operators: ["CONTAINS"],
    widget: "textarea",
    placeholder: undefined,
    multiSelect: undefined,
    enumValues: undefined,
    fullText: { vectorField: "descriptionSearchVector", config: "english" },
  },
  {
    key: "product.handle",
    label: "Handle",
    scope: "product",
    plane: "FAST",
    valueKind: "string",
    operators: ["EQ", "NEQ", "IN", "NOT_IN", "CONTAINS", "NOT_CONTAINS", "STARTS_WITH", "ENDS_WITH", "IS_SET", "IS_NOT_SET"],
    widget: "text",
    placeholder: undefined,
    multiSelect: true,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "product.id",
    label: "Product ID",
    scope: "product",
    plane: "FAST",
    valueKind: "string",
    operators: ["EQ", "NEQ", "IN", "NOT_IN", "CONTAINS", "NOT_CONTAINS", "STARTS_WITH", "ENDS_WITH", "IS_SET", "IS_NOT_SET"],
    widget: "text",
    placeholder: undefined,
    multiSelect: true,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "product.inventoryQuantity",
    label: "Total Inventory",
    scope: "product",
    plane: "FAST",
    valueKind: "number",
    operators: ["EQ", "NEQ", "GT", "GTE", "LT", "LTE", "BETWEEN", "IN", "NOT_IN", "IS_SET", "IS_NOT_SET"],
    widget: "number",
    placeholder: undefined,
    multiSelect: undefined,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "product.option1Name",
    label: "Option 1 Name",
    scope: "product",
    plane: "FAST",
    valueKind: "string",
    operators: ["EQ", "NEQ", "IN", "NOT_IN", "CONTAINS", "NOT_CONTAINS", "STARTS_WITH", "ENDS_WITH", "IS_SET", "IS_NOT_SET"],
    widget: "text",
    placeholder: undefined,
    multiSelect: true,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "product.option2Name",
    label: "Option 2 Name",
    scope: "product",
    plane: "FAST",
    valueKind: "string",
    operators: ["EQ", "NEQ", "IN", "NOT_IN", "CONTAINS", "NOT_CONTAINS", "STARTS_WITH", "ENDS_WITH", "IS_SET", "IS_NOT_SET"],
    widget: "text",
    placeholder: undefined,
    multiSelect: true,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "product.option3Name",
    label: "Option 3 Name",
    scope: "product",
    plane: "FAST",
    valueKind: "string",
    operators: ["EQ", "NEQ", "IN", "NOT_IN", "CONTAINS", "NOT_CONTAINS", "STARTS_WITH", "ENDS_WITH", "IS_SET", "IS_NOT_SET"],
    widget: "text",
    placeholder: undefined,
    multiSelect: true,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "product.productType",
    label: "Product Type",
    scope: "product",
    plane: "FAST",
    valueKind: "string",
    operators: ["EQ", "NEQ", "IN", "NOT_IN", "CONTAINS", "NOT_CONTAINS", "STARTS_WITH", "ENDS_WITH", "IS_SET", "IS_NOT_SET"],
    widget: "text",
    placeholder: undefined,
    multiSelect: true,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "product.publishedAt",
    label: "Date Published",
    scope: "product",
    plane: "FAST",
    valueKind: "date",
    operators: ["EQ", "NEQ", "GT", "GTE", "LT", "LTE", "BETWEEN", "IS_SET", "IS_NOT_SET"],
    widget: "date",
    placeholder: undefined,
    multiSelect: undefined,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "product.searchEngineVisibility",
    label: "SEO Visibility",
    scope: "product",
    plane: "SNAPSHOT",
    valueKind: "enum",
    operators: ["EQ", "NEQ", "IN", "NOT_IN"],
    widget: "select",
    placeholder: undefined,
    multiSelect: true,
    enumValues: [{ value: "visible", label: "Visible" }, { value: "hidden", label: "Hidden" }],
    fullText: undefined,
  },
  {
    key: "product.seoDescription",
    label: "SEO Description",
    scope: "product",
    plane: "FAST",
    valueKind: "text",
    operators: ["CONTAINS"],
    widget: "textarea",
    placeholder: undefined,
    multiSelect: undefined,
    enumValues: undefined,
    fullText: { vectorField: "seoDescriptionSearchVector", config: "english" },
  },
  {
    key: "product.seoTitle",
    label: "SEO Title",
    scope: "product",
    plane: "FAST",
    valueKind: "text",
    operators: ["CONTAINS"],
    widget: "text",
    placeholder: undefined,
    multiSelect: undefined,
    enumValues: undefined,
    fullText: { vectorField: "seoTitleSearchVector", config: "english" },
  },
  {
    key: "product.status",
    label: "Status",
    scope: "product",
    plane: "FAST",
    valueKind: "enum",
    operators: ["EQ", "NEQ", "IN", "NOT_IN"],
    widget: "select",
    placeholder: undefined,
    multiSelect: true,
    enumValues: [{ value: "active", label: "Active" }, { value: "draft", label: "Draft" }, { value: "archived", label: "Archived" }],
    fullText: undefined,
  },
  {
    key: "product.tag",
    label: "Tag",
    scope: "product",
    plane: "FAST",
    valueKind: "string",
    operators: ["EQ", "NEQ", "IN", "NOT_IN", "IS_SET", "IS_NOT_SET"],
    widget: "text",
    placeholder: undefined,
    multiSelect: true,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "product.template",
    label: "Template",
    scope: "product",
    plane: "FAST",
    valueKind: "string",
    operators: ["EQ", "NEQ", "IN", "NOT_IN", "CONTAINS", "NOT_CONTAINS", "STARTS_WITH", "ENDS_WITH", "IS_SET", "IS_NOT_SET"],
    widget: "text",
    placeholder: undefined,
    multiSelect: true,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "product.title",
    label: "Title",
    scope: "product",
    plane: "FAST",
    valueKind: "text",
    operators: ["CONTAINS"],
    widget: "text",
    placeholder: undefined,
    multiSelect: undefined,
    enumValues: undefined,
    fullText: { vectorField: "titleSearchVector", config: "english" },
  },
  {
    key: "product.updatedAt",
    label: "Date Updated",
    scope: "product",
    plane: "FAST",
    valueKind: "date",
    operators: ["EQ", "NEQ", "GT", "GTE", "LT", "LTE", "BETWEEN", "IS_SET", "IS_NOT_SET"],
    widget: "date",
    placeholder: undefined,
    multiSelect: undefined,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "product.variantCount",
    label: "Variant Count",
    scope: "product",
    plane: "FAST",
    valueKind: "number",
    operators: ["EQ", "NEQ", "GT", "GTE", "LT", "LTE", "BETWEEN", "IN", "NOT_IN", "IS_SET", "IS_NOT_SET"],
    widget: "number",
    placeholder: undefined,
    multiSelect: undefined,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "product.vendor",
    label: "Vendor",
    scope: "product",
    plane: "FAST",
    valueKind: "string",
    operators: ["EQ", "NEQ", "IN", "NOT_IN", "CONTAINS", "NOT_CONTAINS", "STARTS_WITH", "ENDS_WITH", "IS_SET", "IS_NOT_SET"],
    widget: "text",
    placeholder: undefined,
    multiSelect: true,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "product.visibleOnlineStore",
    label: "Online Store Visible",
    scope: "product",
    plane: "FAST",
    valueKind: "boolean",
    operators: ["EQ", "NEQ", "IS_SET", "IS_NOT_SET"],
    widget: "boolean-toggle",
    placeholder: undefined,
    multiSelect: undefined,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "product.visiblePos",
    label: "POS Visible",
    scope: "product",
    plane: "FAST",
    valueKind: "boolean",
    operators: ["EQ", "NEQ", "IS_SET", "IS_NOT_SET"],
    widget: "boolean-toggle",
    placeholder: undefined,
    multiSelect: undefined,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "variant.barcode",
    label: "Barcode",
    scope: "variant",
    plane: "FAST",
    valueKind: "string",
    operators: ["EQ", "NEQ", "IN", "NOT_IN", "CONTAINS", "NOT_CONTAINS", "STARTS_WITH", "ENDS_WITH", "IS_SET", "IS_NOT_SET"],
    widget: "text",
    placeholder: undefined,
    multiSelect: true,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "variant.chargeTax",
    label: "Charge Tax",
    scope: "variant",
    plane: "FAST",
    valueKind: "boolean",
    operators: ["EQ", "NEQ", "IS_SET", "IS_NOT_SET"],
    widget: "boolean-toggle",
    placeholder: undefined,
    multiSelect: undefined,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "variant.compareAtPrice",
    label: "Compare At Price",
    scope: "variant",
    plane: "FAST",
    valueKind: "number",
    operators: ["EQ", "NEQ", "GT", "GTE", "LT", "LTE", "BETWEEN", "IN", "NOT_IN", "IS_SET", "IS_NOT_SET"],
    widget: "number",
    placeholder: undefined,
    multiSelect: undefined,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "variant.cost",
    label: "Cost",
    scope: "variant",
    plane: "FAST",
    valueKind: "number",
    operators: ["EQ", "NEQ", "GT", "GTE", "LT", "LTE", "BETWEEN", "IN", "NOT_IN", "IS_SET", "IS_NOT_SET"],
    widget: "number",
    placeholder: undefined,
    multiSelect: undefined,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "variant.countryOfOrigin",
    label: "Country of Origin",
    scope: "variant",
    plane: "FAST",
    valueKind: "string",
    operators: ["EQ", "NEQ", "IN", "NOT_IN", "CONTAINS", "NOT_CONTAINS", "STARTS_WITH", "ENDS_WITH", "IS_SET", "IS_NOT_SET"],
    widget: "text",
    placeholder: undefined,
    multiSelect: true,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "variant.hsTariffCode",
    label: "HS Tariff Code",
    scope: "variant",
    plane: "FAST",
    valueKind: "string",
    operators: ["EQ", "NEQ", "IN", "NOT_IN", "CONTAINS", "NOT_CONTAINS", "STARTS_WITH", "ENDS_WITH", "IS_SET", "IS_NOT_SET"],
    widget: "text",
    placeholder: undefined,
    multiSelect: true,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "variant.inventoryLocation",
    label: "Inventory Location",
    scope: "variant",
    plane: "FAST",
    valueKind: "string",
    operators: ["EQ", "NEQ", "IN", "NOT_IN", "CONTAINS", "NOT_CONTAINS", "STARTS_WITH", "ENDS_WITH", "IS_SET", "IS_NOT_SET"],
    widget: "text",
    placeholder: undefined,
    multiSelect: true,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "variant.inventoryPolicy",
    label: "Inventory Policy",
    scope: "variant",
    plane: "FAST",
    valueKind: "enum",
    operators: ["EQ", "NEQ", "IN", "NOT_IN"],
    widget: "select",
    placeholder: undefined,
    multiSelect: true,
    enumValues: [{ value: "deny", label: "Deny" }, { value: "continue", label: "Continue" }],
    fullText: undefined,
  },
  {
    key: "variant.inventoryQuantity",
    label: "Inventory Quantity",
    scope: "variant",
    plane: "FAST",
    valueKind: "number",
    operators: ["EQ", "NEQ", "GT", "GTE", "LT", "LTE", "BETWEEN", "IN", "NOT_IN", "IS_SET", "IS_NOT_SET"],
    widget: "number",
    placeholder: undefined,
    multiSelect: undefined,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "variant.option1Value",
    label: "Option 1 Value",
    scope: "variant",
    plane: "FAST",
    valueKind: "string",
    operators: ["EQ", "NEQ", "IN", "NOT_IN", "CONTAINS", "NOT_CONTAINS", "STARTS_WITH", "ENDS_WITH", "IS_SET", "IS_NOT_SET"],
    widget: "text",
    placeholder: undefined,
    multiSelect: true,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "variant.option2Value",
    label: "Option 2 Value",
    scope: "variant",
    plane: "FAST",
    valueKind: "string",
    operators: ["EQ", "NEQ", "IN", "NOT_IN", "CONTAINS", "NOT_CONTAINS", "STARTS_WITH", "ENDS_WITH", "IS_SET", "IS_NOT_SET"],
    widget: "text",
    placeholder: undefined,
    multiSelect: true,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "variant.option3Value",
    label: "Option 3 Value",
    scope: "variant",
    plane: "FAST",
    valueKind: "string",
    operators: ["EQ", "NEQ", "IN", "NOT_IN", "CONTAINS", "NOT_CONTAINS", "STARTS_WITH", "ENDS_WITH", "IS_SET", "IS_NOT_SET"],
    widget: "text",
    placeholder: undefined,
    multiSelect: true,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "variant.physicalProduct",
    label: "Requires Shipping",
    scope: "variant",
    plane: "FAST",
    valueKind: "boolean",
    operators: ["EQ", "NEQ", "IS_SET", "IS_NOT_SET"],
    widget: "boolean-toggle",
    placeholder: undefined,
    multiSelect: undefined,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "variant.price",
    label: "Price",
    scope: "variant",
    plane: "FAST",
    valueKind: "number",
    operators: ["EQ", "NEQ", "GT", "GTE", "LT", "LTE", "BETWEEN", "IN", "NOT_IN", "IS_SET", "IS_NOT_SET"],
    widget: "number",
    placeholder: undefined,
    multiSelect: undefined,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "variant.profitMargin",
    label: "Profit Margin",
    scope: "variant",
    plane: "FAST",
    valueKind: "number",
    operators: ["EQ", "NEQ", "GT", "GTE", "LT", "LTE", "BETWEEN", "IN", "NOT_IN", "IS_SET", "IS_NOT_SET"],
    widget: "number",
    placeholder: undefined,
    multiSelect: undefined,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "variant.sku",
    label: "SKU",
    scope: "variant",
    plane: "FAST",
    valueKind: "string",
    operators: ["EQ", "NEQ", "IN", "NOT_IN", "CONTAINS", "NOT_CONTAINS", "STARTS_WITH", "ENDS_WITH", "IS_SET", "IS_NOT_SET"],
    widget: "text",
    placeholder: undefined,
    multiSelect: true,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "variant.title",
    label: "Variant Title",
    scope: "variant",
    plane: "FAST",
    valueKind: "string",
    operators: ["EQ", "NEQ", "IN", "NOT_IN", "CONTAINS", "NOT_CONTAINS", "STARTS_WITH", "ENDS_WITH", "IS_SET", "IS_NOT_SET"],
    widget: "text",
    placeholder: undefined,
    multiSelect: true,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "variant.trackQuantity",
    label: "Track Quantity",
    scope: "variant",
    plane: "FAST",
    valueKind: "boolean",
    operators: ["EQ", "NEQ", "IS_SET", "IS_NOT_SET"],
    widget: "boolean-toggle",
    placeholder: undefined,
    multiSelect: undefined,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "variant.weight",
    label: "Weight",
    scope: "variant",
    plane: "FAST",
    valueKind: "number",
    operators: ["EQ", "NEQ", "GT", "GTE", "LT", "LTE", "BETWEEN", "IN", "NOT_IN", "IS_SET", "IS_NOT_SET"],
    widget: "number",
    placeholder: undefined,
    multiSelect: undefined,
    enumValues: undefined,
    fullText: undefined,
  },
  {
    key: "variant.weightUnit",
    label: "Weight Unit",
    scope: "variant",
    plane: "FAST",
    valueKind: "enum",
    operators: ["EQ", "NEQ", "IN", "NOT_IN"],
    widget: "select",
    placeholder: undefined,
    multiSelect: true,
    enumValues: [{ value: "g", label: "Grams" }, { value: "kg", label: "Kilograms" }, { value: "oz", label: "Ounces" }, { value: "lb", label: "Pounds" }],
    fullText: undefined,
  }
];
