// FILE: web/types/filter.types.ts
//
// Single source of truth for all filter, product, and variant types.
// These mirror the GraphQL schema exactly — any schema change must be
// reflected here. The types are intentionally NOT generated by codegen
// so they can live alongside business logic without a build step.
//
// Barrel: re-exported from web/types/index.ts

// ─────────────────────────────────────────────────────────────────────────────
// Primitive enums  —  mirror GraphQL enums 1:1
// ─────────────────────────────────────────────────────────────────────────────

export type FilterOperator =
  | "EQ"
  | "NEQ"
  | "GT"
  | "GTE"
  | "LT"
  | "LTE"
  | "BETWEEN"
  | "IN"
  | "NOT_IN"
  | "CONTAINS"
  | "NOT_CONTAINS"
  | "STARTS_WITH"
  | "ENDS_WITH"
  | "IS_EMPTY"
  | "IS_NOT_EMPTY"
  | "IS"
  | "ON"
  | "BEFORE"
  | "AFTER";

export type FilterGroupOperator = "AND" | "OR";

export type SortKey =
  | "CREATED_AT"
  | "UPDATED_AT"
  | "PUBLISHED_AT"
  | "TITLE"
  | "VENDOR"
  | "TOTAL_INVENTORY"
  | "VARIANT_COUNT"
  | "VARIANT_PRICE"
  | "VARIANT_SKU"
  | "VARIANT_INVENTORY_QUANTITY";

export type SortDirection = "ASC" | "DESC";

export type FilterLevel = "PRODUCT" | "VARIANT";

export type FilterValueType = "STRING" | "NUMBER" | "BOOLEAN" | "DATE" | "ENUM";

export type PresetKey =
  | "LOW_INVENTORY_VARIANT"
  | "LOW_INVENTORY_PRODUCT"
  | "NO_SEO_VISIBILITY_HIDDEN"
  | "MISSING_IMAGES"
  | "NO_SKU"
  | "NO_BARCODE"
  | "DRAFT_PRODUCTS"
  | "ARCHIVED_PRODUCTS"
  | "OUT_OF_STOCK"
  | "HIGH_COMPARE_AT_DISCOUNT"
  | "MISSING_COST";

export type ProductStatus = "active" | "draft" | "archived";
export type WeightUnit = "g" | "kg" | "oz" | "lb";
export type InventoryPolicy = "deny" | "continue";
export type FulfillmentService = "manual" | "shopify" | "third_party";
export type VariantAvailability = "in_stock" | "out_of_stock" | "on_backorder";

// A future-safe alias so we can later tighten this to a union of OPS keys.
export type FilterKey = string;

// ─────────────────────────────────────────────────────────────────────────────
// Filter value types  —  what value each operator class accepts
// ─────────────────────────────────────────────────────────────────────────────

/** Operators that take a single scalar value */
export type ScalarOperator =
  | "EQ"
  | "NEQ"
  | "GT"
  | "GTE"
  | "LT"
  | "LTE"
  | "ON"
  | "BEFORE"
  | "AFTER";

/** Operators that take a [from, to] tuple */
export type RangeOperator = "BETWEEN";

/** Operators that take an array of values */
export type ArrayOperator = "IN" | "NOT_IN";

/** Operators that take a string value */
export type StringPatternOperator =
  | "CONTAINS"
  | "NOT_CONTAINS"
  | "STARTS_WITH"
  | "ENDS_WITH";

/** Operators that take a boolean value */
export type BooleanOperator = "IS";

/** Operators that take no value (null) */
export type NullaryOperator = "IS_EMPTY" | "IS_NOT_EMPTY";

/**
 * Discriminated union for a typed filter condition value.
 * Ensures you can't pair BETWEEN with a string or IS with an array.
 *
 * NOTE: Dates are always sent as ISO strings to GraphQL, so we restrict to
 * string | number here to match the wire format.
 */
export type FilterConditionValue =
  | { operator: ScalarOperator;        value: string | number }
  | { operator: RangeOperator;         value: [string | number, string | number] }
  | { operator: ArrayOperator;         value: Array<string | number> }
  | { operator: StringPatternOperator; value: string }
  | { operator: BooleanOperator;       value: boolean }
  | { operator: NullaryOperator;       value?: null | undefined };

// ─────────────────────────────────────────────────────────────────────────────
// Filter DSL input types  —  what the client sends to GraphQL
// ─────────────────────────────────────────────────────────────────────────────

export interface FilterConditionInput {
  readonly key:      FilterKey;
  readonly operator: FilterOperator;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  readonly value?:   any;           // JSON scalar — runtime-validated by server
}

export interface FilterGroupInput {
  readonly operator:   FilterGroupOperator;
  readonly conditions?: ReadonlyArray<FilterConditionInput>;
  readonly groups?:     ReadonlyArray<FilterGroupInput>;
}

export interface PaginationInput {
  readonly page?:     number;
  readonly pageSize?: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// Filter registry  —  what the server returns for the UI filter-builder
// ─────────────────────────────────────────────────────────────────────────────

export interface FilterDefinition {
  readonly key:        FilterKey;
  readonly label:      string;
  readonly level:      FilterLevel;
  readonly valueType:  FilterValueType;
  readonly operators:  ReadonlyArray<FilterOperator>;
  readonly sortable:   boolean;
  readonly isComputed: boolean;
  readonly enumValues: ReadonlyArray<string> | null;
}

export interface FilterRegistryPayload {
  readonly productFilters: ReadonlyArray<FilterDefinition>;
  readonly variantFilters: ReadonlyArray<FilterDefinition>;
  readonly allFilters:     ReadonlyArray<FilterDefinition>;
}

export interface SortDefinition {
  readonly key:                 SortKey;
  readonly defaultDirection:    SortDirection;
  readonly requiresVariantJoin: boolean;
}

export interface PresetDefinition {
  readonly key:         PresetKey;
  readonly label:       string;
  readonly description: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Filter validation
// ─────────────────────────────────────────────────────────────────────────────

export interface FilterValidationError {
  readonly path:    string;
  readonly message: string;
}

export interface FilterValidationResult {
  readonly valid:  boolean;
  readonly errors: ReadonlyArray<FilterValidationError>;
}

// ─────────────────────────────────────────────────────────────────────────────
// Pagination output
// ─────────────────────────────────────────────────────────────────────────────

export interface PageInfo {
  readonly page:        number;
  readonly pageSize:    number;
  readonly totalCount:  number;
  readonly totalPages:  number;
  readonly hasNextPage: boolean;
  readonly hasPrevPage: boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
// Product row  —  matches GraphQL ProductRow type exactly
// ─────────────────────────────────────────────────────────────────────────────

export interface ProductRow {
  readonly id:                  string;
  readonly shopId:              number;
  readonly shopifyProductId:    string;
  readonly title:               string;
  readonly handle:              string;
  readonly vendor:              string | null;
  readonly status:              ProductStatus;
  readonly createdAt:           string;       // ISO 8601
  readonly publishedAt:         string | null;
  readonly updatedAt:           string;
  readonly rollupInventoryQty:  number;
  readonly variantCount:        number;
  readonly imageCount:          number;
  readonly category:            string | null;
  readonly productTypeCustom:   string | null;
  readonly seoHidden:           boolean;
  readonly templateSuffix:      string | null;
  readonly visibleOnlineStore:  boolean;
  readonly visiblePos:          boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
// Variant row  —  matches GraphQL VariantRow type exactly
// ─────────────────────────────────────────────────────────────────────────────

export interface VariantRow {
  // Variant-specific fields
  readonly variantId:           string;
  readonly shopId:              number;
  readonly shopifyVariantId:    string;
  readonly shopifyProductId:    string;
  readonly variantTitle:        string;
  readonly sku:                 string | null;
  readonly barcode:             string | null;
  readonly price:               string;       // money as string — never float
  readonly compareAtPrice:      string | null;
  readonly cost:                string | null;
  readonly profitMarginPct:     number | null;
  readonly inventoryQuantity:   number;
  readonly trackQuantity:       boolean;
  readonly taxable:             boolean;
  readonly requiresShipping:    boolean;
  readonly weight:              number | null;
  readonly weightUnit:          WeightUnit | null;
  readonly grams:               number | null;
  readonly option1Value:        string | null;
  readonly option2Value:        string | null;
  readonly option3Value:        string | null;
  readonly inventoryPolicy:     InventoryPolicy | null;
  readonly fulfillmentService:  FulfillmentService | null;
  readonly availability:        VariantAvailability | null;

  // Parent product rollup
  readonly productId:           string;
  readonly productTitle:        string;
  readonly handle:              string;
  readonly vendor:              string | null;
  readonly status:              ProductStatus;
  readonly rollupInventoryQty:  number;
  readonly variantCount:        number;
  readonly imageCount:          number;
  readonly category:            string | null;
  readonly productTypeCustom:   string | null;
  readonly visibleOnlineStore:  boolean;
  readonly visiblePos:          boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
// Connection (paginated list) types
// ─────────────────────────────────────────────────────────────────────────────

export interface ProductConnection {
  readonly pageInfo: PageInfo;
  readonly items:    ReadonlyArray<ProductRow>;
}

export interface VariantConnection {
  readonly pageInfo: PageInfo;
  readonly items:    ReadonlyArray<VariantRow>;
}

// ─────────────────────────────────────────────────────────────────────────────
// Hook option types  —  what callers pass to useProductsByFilter etc.
// ─────────────────────────────────────────────────────────────────────────────

export interface UseProductsOptions {
  filter?:     FilterGroupInput | null;
  sort?:       SortKey;
  direction?:  SortDirection;
  page?:       number;
  pageSize?:   number;
  /** Skip the query entirely (e.g. component not mounted yet) */
  skip?:       boolean;
}

export interface UseVariantsOptions {
  filter?:     FilterGroupInput | null;
  sort?:       SortKey;
  direction?:  SortDirection;
  page?:       number;
  pageSize?:   number;
  skip?:       boolean;
}

export interface UsePresetProductsOptions {
  preset:       PresetKey;
  threshold?:   number;
  page?:        number;
  pageSize?:    number;
  skip?:        boolean;
}

export interface UsePresetVariantsOptions {
  preset:       PresetKey;
  threshold?:   number;
  page?:        number;
  pageSize?:    number;
  skip?:        boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
// Hook return types
// ─────────────────────────────────────────────────────────────────────────────

export interface UseProductsResult {
  items:       ReadonlyArray<ProductRow>;
  pageInfo:    PageInfo | null;
  loading:     boolean;
  error:       Error | null;
  /** Refetch the current query with the same variables */
  refetch:     () => Promise<void>;
}

export interface UseVariantsResult {
  items:       ReadonlyArray<VariantRow>;
  pageInfo:    PageInfo | null;
  loading:     boolean;
  error:       Error | null;
  refetch:     () => Promise<void>;
}

export interface UseFilterRegistryResult {
  registry:    FilterRegistryPayload | null;
  sortDefs:    ReadonlyArray<SortDefinition>;
  presetDefs:  ReadonlyArray<PresetDefinition>;
  loading:     boolean;
  error:       Error | null;
}

export interface UseFilterValidationResult {
  validate:    (filter: FilterGroupInput) => Promise<FilterValidationResult>;
  validating:  boolean;
  lastResult:  FilterValidationResult | null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Filter builder state types  —  for useFilterBuilder hook
// ─────────────────────────────────────────────────────────────────────────────

/** A mutable (draft) version of FilterConditionInput — used in the UI before submitting */
export interface FilterConditionDraft {
  readonly id:        string;          // stable React key (nanoid)
  key:                FilterKey;
  operator:           FilterOperator;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  value:              any;
  validationError?:   string | null;
}

export interface FilterGroupDraft {
  readonly id:    string;
  operator:       FilterGroupOperator;
  conditions:     FilterConditionDraft[];
  groups:         FilterGroupDraft[];
}

export interface UseFilterBuilderResult {
  /** Current draft state */
  draft:          FilterGroupDraft;
  /** Convert draft → FilterGroupInput for the query */
  toInput:        () => FilterGroupInput | null;
  /** Mutations */
  setOperator:    (groupId: string, op: FilterGroupOperator) => void;
  addCondition:   (groupId: string, key: FilterKey) => void;
  updateCondition:(groupId: string, condId: string, patch: Partial<FilterConditionDraft>) => void;
  removeCondition:(groupId: string, condId: string) => void;
  addGroup:       (parentGroupId: string) => void;
  removeGroup:    (groupId: string) => void;
  reset:          () => void;
  /** Whether the draft produces a non-empty filter */
  isEmpty:        boolean;
}